# Generated by Django 4.1.7 on 2023-07-23 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=360)),
                ('target_audience', models.TextField()),
                ('experience_years', models.CharField(max_length=360)),
                ('reach_range', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('website', models.CharField(max_length=360)),
                ('mail', models.EmailField(max_length=100)),
                ('schedule', models.CharField(max_length=360)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('copy_languages', models.CharField(max_length=100)),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('values', models.TextField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartContentBackendClientsAndBusinessApp.address')),
            ],
            options={
                'db_table': 'businesses',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=360)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'industries',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartContentBackendClientsAndBusinessApp.business')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password_hash', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('profile_picture', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='PostTracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.CharField(max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartContentBackendClientsAndBusinessApp.post')),
            ],
            options={
                'db_table': 'post_tracking',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chosen', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartContentBackendClientsAndBusinessApp.post')),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SmartContentBackendClientsAndBusinessApp.message')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_picture', models.CharField(max_length=255)),
                ('address_id', models.ForeignKey(db_column='address_id', on_delete=django.db.models.deletion.CASCADE, to='SmartContentBackendClientsAndBusinessApp.address')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='SmartContentBackendClientsAndBusinessApp.user')),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='BusinessAddressPreferences',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartContentBackendClientsAndBusinessApp.address')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartContentBackendClientsAndBusinessApp.business')),
            ],
            options={
                'db_table': 'businesses_address_preferences',
            },
        ),
        migrations.AddField(
            model_name='business',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartContentBackendClientsAndBusinessApp.client'),
        ),
        migrations.AddField(
            model_name='business',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartContentBackendClientsAndBusinessApp.industry'),
        ),
    ]
