# Generated by Django 4.1.7 on 2023-07-23 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartContentBackendClientsAndBusinessApp', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""

          DROP PROCEDURE IF EXISTS insert_client;

          CREATE PROCEDURE insert_client(
          IN p_first_name VARCHAR(255), 
          IN p_last_name VARCHAR(255), 
          IN p_address_id INT, 
          IN p_email VARCHAR(255), 
          IN p_phone VARCHAR(15), 
          IN p_profile_picture VARCHAR(255),
          IN p_user_id INT)
          BEGIN
          
           INSERT INTO clients(first_name, last_name, address_id, email, phone, profile_picture, user_id,created_at)
                VALUES (p_first_name, p_last_name, p_address_id, p_email, p_phone, p_profile_picture, p_user_id,now());
            END 
        """)
    ]
