# Generated by Django 4.1.7 on 2023-07-23 23:22


from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('SmartContentBackendClientsAndBusinessApp', '0003_update_client'),
    ]

    operations = [
        migrations.RunSQL("""

          DROP PROCEDURE IF EXISTS delete_client;

          CREATE PROCEDURE delete_client(IN p_client_id INT)
          BEGIN
          
            UPDATE clients
            SET deleted_at = NOW()
            WHERE id = p_client_id;
            
          END 
        """)
    ]




