# Generated by Django 4.1.7 on 2023-07-23 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartContentBackendClientsAndBusinessApp', '0005_get_all_clients'),
    ]

    operations = [
    ]
