# Generated by Django 4.1.7 on 2023-07-23 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartContentBackendClientsAndBusinessApp', '0004_delete_client'),
    ]

    operations = [
    ]
