# Generated by Django 4.1.7 on 2023-07-23 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartContentBackendClientsAndBusinessApp', '0006_get_client_by_id'),
    ]

    operations = [
        migrations.RunSQL("""

          DROP PROCEDURE IF EXISTS insert_industry;

          CREATE PROCEDURE insert_industry(
          IN p_name VARCHAR(360))
          BEGIN
          
           INSERT INTO industries(name, created_at)
                VALUES (p_name, now());
          END 
        """)
    ]