# Generated by Django 4.1.7 on 2023-07-23 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartContentBackendClientsAndBusinessApp', '0009_delete_industry'),
    ]

    operations = [
    ]
