# Generated by Django 4.1.7 on 2023-07-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartContentBackendClientsAndBusinessApp', '0011_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
