# Generated by Django 4.1.7 on 2023-07-24 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartContentBackendClientsAndBusinessApp', '0016_delete_address'),
    ]

    operations = [
    ]
