# Generated by Django 4.1.7 on 2023-07-24 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartContentBackendClientsAndBusinessApp', '0018_client_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='business',
        ),
        migrations.RemoveField(
            model_name='posttracking',
            name='post',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostTracking',
        ),
    ]
