# Generated by Django 4.1.7 on 2023-07-23 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartContentBackendClientsAndBusinessApp', '0020_client_deleted_at'),
    ]

    operations = [
        migrations.RunSQL("""
            DROP PROCEDURE IF EXISTS insert_business;

            CREATE PROCEDURE insert_business(
            IN p_name VARCHAR(360),
            IN p_target_audience TEXT,
            IN p_experience_years VARCHAR(360),
            IN p_reach_range INT,
            IN p_phone VARCHAR(360),
            IN p_address_id INT,
            IN p_website VARCHAR(360),
            IN p_mail VARCHAR(100),
            IN p_industry_id INT,
            IN p_schedule VARCHAR(360),
            IN p_copy_languages VARCHAR(100),
            IN p_client_id INT,
            IN p_mission TEXT,
            IN p_vision TEXT,
            IN p_values TEXT)
            BEGIN
                INSERT INTO businesses(name, target_audience, experience_years, reach_range, phone, 
                address_id, website, mail, industry_id, schedule, created_at, copy_languages, 
                client_id, mission, vision, `values`)
                VALUES (p_name, p_target_audience, p_experience_years, p_reach_range, p_phone, 
                p_address_id, p_website, p_mail, p_industry_id, p_schedule, now(), p_copy_languages, 
                p_client_id, p_mission, p_vision, p_values);
            END
        """)
    ]
