# Generated by Django 4.1.7 on 2023-07-23 23:45

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('SmartContentBackendClientsAndBusinessApp', '0021_insert_business'),
    ]

    operations = [
        migrations.RunSQL("""
            DROP PROCEDURE IF EXISTS update_business;

            CREATE PROCEDURE update_business(
            IN p_business_id INT,
            IN p_name VARCHAR(360),
            IN p_target_audience TEXT,
            IN p_experience_years VARCHAR(360),
            IN p_reach_range INT,
            IN p_phone BIGINT,
            IN p_address_id INT,
            IN p_website VARCHAR(360),
            IN p_mail VARCHAR(100),
            IN p_industry_id INT,
            IN p_schedule VARCHAR(360),
            IN p_copy_languages VARCHAR(100),
            IN p_client_id INT,
            IN p_mission TEXT,
            IN p_vision TEXT,
            IN p_values TEXT)
            BEGIN
                UPDATE businesses
                SET name = p_name,
                    target_audience = p_target_audience,
                    experience_years = p_experience_years,
                    reach_range = p_reach_range,
                    phone = p_phone,
                    address_id = p_address_id,
                    website = p_website,
                    mail = p_mail,
                    industry_id = p_industry_id,
                    schedule = p_schedule,
                    copy_languages = p_copy_languages,
                    client_id = p_client_id,
                    mission = p_mission,
                    vision = p_vision,
                    `values` = p_values
                WHERE id = p_business_id;
            END
        """)
    ]
