# Generated by Django 4.1.7 on 2023-07-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartContentBackendClientsAndBusinessApp', '0021_insert_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
