# Generated by Django 4.1.7 on 2023-08-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartContentBackendClientsAndBusinessApp', '0023_business_deleted_at_business_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.TextField(),
        ),
    ]
