# Generated by Django 4.1.7 on 2023-08-12 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartContentBackendClientsAndBusinessApp', '0024_alter_business_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=360)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('business_id', models.ForeignKey(db_column='business_id', on_delete=django.db.models.deletion.CASCADE, to='SmartContentBackendClientsAndBusinessApp.business')),
            ],
            options={
                'db_table': 'copies',
            },
        ),
    ]
