# Generated by Django 4.1.7 on 2023-08-26 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartContentBackendClientsAndBusinessApp', '0025_copies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=360)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='ServiceBusiness',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone', models.CharField(max_length=255)),
                ('level_importance', models.IntegerField()),
                ('business_id', models.ForeignKey(db_column='business_id', on_delete=django.db.models.deletion.CASCADE, to='SmartContentBackendClientsAndBusinessApp.business')),
                ('service_id', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='SmartContentBackendClientsAndBusinessApp.service')),
            ],
            options={
                'db_table': 'services_business',
            },
        ),
    ]
