# Generated by Django 4.1.7 on 2023-08-26 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartContentBackendClientsAndBusinessApp', '0026_service_servicebusiness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebusiness',
            name='cost_level',
        ),
    ]
