# Generated by Django 4.1.7 on 2023-08-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartContentBackendClientsAndBusinessApp', '0027_remove_servicebusiness_cost_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='experience_years',
            new_name='facebook_page',
        ),
    ]
