# Generated by Django 4.1.7 on 2023-08-27 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartContentBackendClientsAndBusinessApp', '0030_service_created_at_service_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='copy_languages',
        ),
        migrations.RemoveField(
            model_name='business',
            name='reach_range',
        ),
    ]
