# Generated by Django 4.1.7 on 2023-08-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartContentBackendClientsAndBusinessApp', '0031_remove_business_copy_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebusiness',
            name='phone',
        ),
        migrations.AlterField(
            model_name='business',
            name='logo_carpet',
            field=models.TextField(null=True),
        ),
    ]
