# Generated by Django 4.1.7 on 2023-08-27 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartContentBackendClientsAndBusinessApp', '0032_remove_servicebusiness_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebusiness',
            name='cost',
        ),
    ]
