# Generated by Django 4.1.7 on 2023-09-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartContentBackendClientsAndBusinessApp', '0055_get_all_clients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copies',
            old_name='description',
            new_name='copy',
        ),
        migrations.RemoveField(
            model_name='copies',
            name='title',
        ),
        migrations.AddField(
            model_name='copies',
            name='likes',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='copies',
            name='shared',
            field=models.TextField(null=True),
        ),
    ]
