# Generated by Django 4.1.7 on 2023-09-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartContentBackendClientsAndBusinessApp', '0056_rename_description_copies_copy_remove_copies_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copies',
            name='copy',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='copies',
            name='likes',
            field=models.TextField(null=True),
        ),
    ]
