# Generated by Django 4.1.7 on 2023-09-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartContentBackendClientsAndBusinessApp', '0057_alter_copies_copy_alter_copies_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='copies',
            name='flyer_text',
            field=models.TextField(null=True),
        ),
    ]
